spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 'jdbc:sqlserver://localhost:1433;databaseName=demo;trustServerCertificate=true'
    username: sa
    password: M$Dem0Dotne!
    hikari:
      connection-timeout: 3000
  cloud:
    config:
      enabled: false
      username: ADMIN
      password: 123
      label: main
  application:
    name: "WingBank Treasure Hunt"

  mvc:
    log-request-details: true

server:
  port: 8081

jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties:
    hibernate:
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
  shutdown:
    enabled: true

logging:
  level:
    org:
      springframework:
        boot: OFF
        web: OFF

  pattern:
    date-format: yyyy-dd-MM HH:mm:ss.SSS
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-38X{X-CorrelationId:-empty-correlation} %-40logger{0} : %msg%n'

application-config:
  microservices:
    ocs-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/surepay"