spring:
  config:
    import: configserver:${CONFIG_SERVER_URL:https://dev-apiserver.camgsm.com.kh/config-server/v1}

  cloud:
    config:
      enabled: true
      username: ADMIN
      password: 123
      label: main
      profiles: dev

  application:
    name: "ms-api-boilerplate"