spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 'jdbc:sqlserver://localhost:1433;databaseName=demo;trustServerCertificate=true'
    username: sa
    password: M$Dem0Dotne!
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      username: admin
      password: 123
      label: main
  application:
    name: microservice-template

  mvc:
    log-request-details: true

server:
  port: 8080


info:
  app:
    name: microservice-template
    description: spring-boot microservice demo
    version: 1.0.0

jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties:
    hibernate:
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
  shutdown:
    enabled: true


logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-38X{X-CorrelationId:-empty-correlation} %-40logger{0} : %msg%n'