spring:
  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      enabled: true
      username: ADMIN
      password: 123
      label: main
      profiles: dev

  application:
    name: "ms-api-boilerplate"