spring:
  config:
    import: configserver:https://dev-apiserver.camgsm.com.kh/config-server/v1
  cloud:
    bus:
      enabled: true
    config:
      enabled: true
      username: ADMIN
      password: 123
      label: main
      profiles: local

  flyway:
    enabled: false

  application:
    name: "ms-api-boilerplate"