server:
  port: 9090

spring:
  cloud:
    bus:
      enabled: false
    config:
      enabled: false

  application:
    name: ms-api-boilerplate
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATABASE_URL:jdbc:sqlserver://172.16.101.29;instance=SQLEXPRESS;databaseName=STG;encrypt=true;trustServerCertificate=true;}
    username: ${DATABASE_USERNAME:devadmin}
    password: ${DATABASE_PASSWORD:V@!aDmin2020Devusr}
    hikari:
      connection-timeout: 3000

  kafka:
    required: true
    bootstrap-servers: qa-kaf1.camgsm.com.kh:9092
    group-id: sovath-test-1

  redis:
    host: 172.16.101.164
    port: 32075
    password: UOWMh5uVKi
    timeout: 3000

  bus:
    enabled: true

jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties:
    hibernate:
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
  shutdown:
    enabled: true

logging:
  level:
    org:
      springframework:
        boot: ERROR
        web: ERROR
      apache:
        kafka: OFF
      hibernate: OFF

  pattern:
    date-format: yyyy-dd-MM HH:mm:ss.SSS
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%-20.20thread] %-38X{X-CorrelationId:-00000000-0000-0000-0000-000000000000} %-30.30logger{0} : %msg%n'

application-config:
  maintenance-mode: 'OFF'
  maintenance-message: 'Sorry the service is under maintenance! Please try again later.'
  global-request-timeout-millisecond: 5
  global-connect-timeout-millisecond: 10000
  microservices:
    ocs-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/surepay"
      request-timeout-millisecond: 4000
    sms-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/sms-transmit/v1/accounts/%s"
      request-timeout-millisecond: 4000
    billing-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/proxyBilling"
      request-timeout-millisecond: 4000
    sms-catalog-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/ServiceMessageCatalog/v1/ServiceName/{service_name}/get?language={language}&method={method}&error_code={error_code}&type={type}"
      request-timeout-millisecond: 4000
    
  sms-catalogs:
    - system-error:
        code: '0005'
        message:
          kh: 'Issues on system when provisioning your request, khmer'
          en: 'Issues on system when provisioning your request'
        description: 'Invalid Account Id !'
    - invalid-account-id:
        code: '0004'
        message:
          kh: 'Invalid Account Id !, khmer'
          en: 'Invalid Account Id !'
        description: 'Invalid Account Id !'
    - invalid-request-plan:
        code: "0005"
        message:
          kh: 'Invalid request plan. Khmer'
          en: 'Invalid request plan .'
        description: "plan name invalid"

    - subscribe-success:
        code: "0000"
        message:
          en: "You subscribed to Reseller Plus $1. Next Renewal: {next_date}. To check balance dial *1201#"
          kh: "You subscribed to Reseller Plus $1. Next Renewal: {next_date}. To check balance dial *1201#, Khmer"
        description: "Successfully subscribed"

    - subscribe-not-enough-balance:
        code: "0001"
        message:
          en: "Not enough balance."
          kh: "Not enough balance. Khmer"
        description: "not enough balance"




